---
- include: init.yml

- name: Create directory
  file: path={{ directory }} state=directory
- name: Copy Docker-compose configuration
  template: src=docker-compose.yml dest={{ directory }}/

- name: Copy Elasticsearch configuration
  file: path={{ directory }}/config/elasticsearch/ state=directory
- template: src=elasticsearch.yml dest={{ directory }}/config/elasticsearch/
  notify: Restart Elasticsearch
- copy: src=logging.yml dest={{ directory }}/config/elasticsearch/
#  notify: Restart Elasticsearch

- name: Copy Logstash configuration
  synchronize: src={{ logstash_configs }}/ dest={{ directory }}/config/logstash/ delete=yes
#  notify: Restart Logstash

- name: Copy Kibana configuration
  file: path={{ directory }}/config/kibana state=directory
- template: src=kibana.yml dest={{ directory }}/config/kibana/
#  notify: Restart Kibana

#Start compose
