---
- include: init.yml

- name: Create directory
  file: path={{ directory }} state=directory

- name: Start Elasticsearch docker container
  docker:
    name: elasticsearch
    image: elasticsearch:{{ elasticsearch_version }}
    pull: always
    volumes:
      - "{{ directory }}/data/:/usr/share/elasticsearch/data/"
    state: started
    restart_policy: always

- name: Copy Logstash configuration
  copy: src={{ logstash_configs }}/ dest={{ directory }}/config/logstash/
- name: Start Logstash docker container
  docker:
    name: logstash
    image: mkuzmin/logstash
    pull: always
    volumes:
      - "{{ directory }}/config/logstash/:/opt/logstash/config/:ro"
    links:
      - "elasticsearch"
    command: -f /opt/logstash/config/config/
    expose:
      - "{{ logstash_port }}"
    ports:
      - "{{ logstash_port }}:{{ logstash_port }}"
    state: started
    restart_policy: always

- name: Create Kibana configuration directory
  file: path={{ directory }}/config/kibana state=directory
- name: Copy Kibana configuration
  template: src=kibana.yml dest={{ directory }}/config/kibana/
- name: Start Kibana docker container
  docker:
    name: kibana
    image: kibana:{{ kibana_version }}
    pull: always
    volumes:
      - "{{ directory }}/config/kibana/:/opt/kibana/config/"
    links:
      - "elasticsearch"
    ports:
      - "{{ kibana_port }}:5601"
    state: started
    restart_policy: always
